### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by clexmond** [ncitron/cairo-merkle-distributor#1]
If you're willing, could you add an open source license (ideally MIT)?

**Comment by ncitron** [comment]
Added the license! Great to see others wanting to use this (although please note that this has not been audited and may contain bugs).

**Comment by clexmond** [comment]
Wonderful, thank you! I have created a javascript version of your merkle utils as well, can I go ahead and submit a PR with it?

**Comment by ncitron** [comment]
Sounds good
